#!/bin/bash
npm install express
npm install compression
npm install express-session
npm install body-parser
npm install morgan
npm install chalk
npm install errorhandler
npm install lusca
npm install dotenv
npm install connect-mongo
npm install express-flash
npm install mongoose
npm install passport
npm install express-validator
npm install express-status-monitor
npm install node-sass-middleware
npm install multer
npm install bluebird
npm install nodemailer
npm install bcrypt-nodejs
npm install request
npm install cheerio
npm install fbgraph
npm install lastfm
npm install tumblr.js
npm install github
npm install twit
npm install stripe
npm install twilio
npm install node-linkedin
npm install clockwork
npm install paypal-rest-sdk
npm install lob
npm install instagram-node
npm install node-foursquare
npm install passport-instagram
npm install passport-local
npm install passport-facebook
npm install passport-twitter
npm install passport-github
npm install passport-google-oauth
npm install passport-linkedin-oauth2
npm install passport-openid
npm install passport-oauth
npm install pug
npm install googlemaps
npm install --save public-ip
npm install geoip-lite
npm install node-mongoose-fixtures
